version: '3'

services:
  # Mailhog
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - wpsite
  # Database
  db:
    container_name: db-${PROJECT}
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin-${PROJECT}
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
#    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 300M
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
  # Wordpress
  phpapache:
    build: .
    depends_on:
      - db
    
    container_name: phpapache-${PROJECT}
#    image: php:8.0-apache
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
    networks:
      - wpsite

  wp-cli:
    container_name: wp-cli-${PROJECT}
    depends_on:
      - phpapache
      - db
    image: wordpress:cli
    user: 1000:1000
    command: tail -f /dev/null
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db_data:
  mailhog:


